### ISSUE TITLE
Use YAML for configuration files

### ISSUE THREAD

**Issue by cmargonis** [micbakos/ReleaseNotes#1]
Hello and thank you for this tool! 💯 

With this issue I'd like to propose an enhancement regarding configuring the script.
The enhancement would be to use [YAML](https://en.wikipedia.org/wiki/YAML) for providing
the configuration, as it is more easily configurable by humans and less verbose than `json`.

Below I've attached a sample of how the configuration would look like, compared with json.
For doing that there are a couple of options when it comes to Kotlin:
- [Hoplite](https://github.com/sksamuel/hoplite)
- [Kaml](https://github.com/charleskorn/kaml)

I'd be happy to provide an upstream change if you would find this change useful 😄 

#### JSON
```javascript
{
  "variants": [
    {
      "name": "passenger",
      "categories": [
        {
          "title": "Product",
          "regex": "taxibeat\\/(passenger|all)\\/(feature)\\/(?!infra).+\\/.+"
        },
        {
          "title": "Infra",
          "regex": "taxibeat\\/(passenger|all)\\/(feature|chapter)\\/infra\\/.+"
        },
        {
          "title": "Bugs",
          "regex": "taxibeat\\/(passenger|all)\\/(bugfix|hotfix)\\/.+"
        }
      ]
    },
    {
      "name": "driver",
      "categories": [
        {
          "title": "Product",
          "regex": "taxibeat\\/(driver|all)\\/(feature)\\/(?!infra).+\\/.+"
        },
        {
          "title": "Infra",
          "regex": "taxibeat\\/(driver|all)\\/(feature|chapter)\\/infra\\/.+"
        },
        {
          "title": "Bugs",
          "regex": "taxibeat\\/(driver|all)\\/(bugfix|hotfix)\\/.+"
        }
      ]
    }
  ],
  "links": [
    {
      "url": "https://jira.taxibeat.com/browse/$1",
      "regex": "\\[(\\D+-\\d+)\\]"
    }
  ]
}
```

#### YAML

```yaml

variants:
 - name: passenger
   categories:
    - title: Product
      regex: taxibeat\/(passenger|all)\/(feature)\/(?!infra).+\/.+
    - title: Infra
      regex: taxibeat\/(passenger|all)\/(feature|chapter)\/infra\/.+
    - title: Bugs
      regex: taxibeat\/(passenger|all)\/(bugfix|hotfix)\/.+
 - name: driver
   categories:
    - title: Product
      regex: taxibeat\/(driver|all)\/(feature)\/(?!infra).+\/.+
    - title: Infra
      regex: taxibeat\/(driver|all)\/(feature|chapter)\/infra\/.+
    - title: Bugs
      regex: taxibeat\/(driver|all)\/(bugfix|hotfix)\/.+
links:
 - url: "https://jira.taxibeat.com/browse/$1"
   regex: '\[(\D+-\d+)\]'


```
